language: node_js
node_js:
- 6.2.0
branches:
  only:
  - master
sudo: required
deploy:
  provider: codedeploy
  access_key_id: AKIAJQ265ZZOT7HY4LLQ
  application: PlayWeather
  deployment_group: production
  region: eu-west-1
  revision_type: github
  wait-until-deployed: true
  on:
    repo: mauriciofs/codeDeployTest
  secret_access_key:
    secure: YHsg5mxVn8FivLjv7tFfCtjTFEAaqZrEoQ5GzQXNCVj2yfgS+xftkWeF77BFiCUAlEnM2epAsLwDE5oT4ADSWRejz2g+B2ya/xiIgOjoNERDkhDw/Fu99XNBmDA9GIlgX0nDIRX5DauBorW/9dXgV0ZVIJnG0E+pJAu9vmPVOkvbUHma4X8YJ+tn34Xh6Nx/AkMDy7skd36H/sQOEKh2DFLEoynNHUub5tAZ749+2s9KAR5yIlNOPpfmH1ll4NLVPKKR3ZXHNUFD8Dy3SqCaG34FIc0JP3H1jakj4ECrgzvldRAYvljFLBg1kEhxStpP91UKj3l2OnH6soBOrzu6r90s5ud7Qktr7cL4f5Y4GR+Oo55EE7DmMX6LaNKLLKAvRcilY2n/wHmLQFx9ZlNjbXrZXe3Y1h7n2PrcSvVJ8CzJ4+iDUXwOgImWXhmYDKhSlAPW1DF89pXb5IiBq0EVGNgerRRZywDoN4WsM9aZStZ2NY5klPkKLjW6TEkqr/q2/ShJaannTTvfO7vZtHs7Dd/w8esPPoMFp2DlmKFiygdO1p/7QtSMTflt8/zJI0XiYoc5AVMACmrC2/gsh7f4teUJMrTBC/IPdB3PWm5OhbNE0q7PwluQCFWcTXqouOP2k1lG7stkCNVCLbxoR6UCRryjHUnC+qsQS7eTWVh7L8c=
